# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: A
  jobs:
  - job: A1
    timeoutInMinutes: 10 # how long to run the job before automatically cancelling  
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo Hello, world! A1
      displayName: 'Run script A1 windows'

  - job: A2
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo "A2"
      displayName: 'Run script A2 ubuntu'

- stage: B
  jobs:
  - job: B1
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    pool:
      vmImage: 'CentOS-latest'
    steps:
    - script: echo Hello, world! B1
      displayName: 'Run script B1 CentOS'

  - job: B2
    dependsOn: B1
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - bash: echo "B2"
      displayName: 'Run script B2 macOS'